"""add payment_method column

Revision ID: 0a3a836a9694
Revises: ba8e1d072d9e
Create Date: 2026-05-02 22:22:41.171598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3a836a9694'
down_revision: Union[str, Sequence[str], None] = 'ba8e1d072d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=20), nullable=False, server_default='card'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_method')
    # ### end Alembic commands ###
